### ISSUE TITLE
I tried to get rid of all the naughty bits

### ISSUE THREAD

**Issue by jocelyn-cuthbert** [pearselab/r-world-jocelyn-cuthbert#2]
So I tried to channel my inner programmer and get rid of all the naughty bits in the terrain square step (line 53).  I successfully in the last hour in getting rid of all the things and also all the errors.  Unfortunately, I am right back where I started.  No errors, but also no doing of the things.  Please send help.

**Comment by willpearse** [comment]
I'm assuming that, now that this has been closed, you've got it fixed, yes?
